language: go

go:
 - tip

before_install:
  - git clone https://github.com/wolfired/clabs.git
  - cd clabs && workspace_git=. workspace_labs=. ./build.sh && cd

script: go test github.com/wolfired/golabs/main/pong

notifications:
 email: false
